### YamlMime:PythonClass
uid: azure.ai.ml.entities.job_errors.JobParsingError
name: JobParsingError
fullName: azure.ai.ml.entities.job_errors.JobParsingError
module: azure.ai.ml.entities.job_errors
inheritances:
- azure.ai.ml.exceptions.MlException
summary: Exception that the job data returned by MFE cannot be parsed.
constructor:
  syntax: JobParsingError(error_category, no_personal_data_message, message, *args,
    **kwargs)
  parameters:
  - name: error_category
  - name: no_personal_data_message
  - name: message
methods:
- uid: azure.ai.ml.entities.job_errors.JobParsingError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.ai.ml.entities.job_errors.JobParsingError.raise_with_traceback
  name: raise_with_traceback
  summary: 'Raise the exception with the existing traceback.


    Deprecated since version 1.22.0: This method is deprecated as we don''t support
    Python 2 anymore. Use raise/from instead.'
  signature: raise_with_traceback() -> None
- uid: azure.ai.ml.entities.job_errors.JobParsingError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.ai.ml.entities.job_errors.JobParsingError.args
  name: args
- uid: azure.ai.ml.entities.job_errors.JobParsingError.error_category
  name: error_category
  summary: Return the error category.
  return:
    description: The error category.
    types:
    - <xref:azure.ai.ml.exceptions.ErrorCategory>
- uid: azure.ai.ml.entities.job_errors.JobParsingError.no_personal_data_message
  name: no_personal_data_message
  summary: Return the error message with no personal data.
  return:
    description: No personal data error message.
    types:
    - <xref:str>
- uid: azure.ai.ml.entities.job_errors.JobParsingError.target
  name: target
  summary: Return the error target.
  return:
    description: The error target.
    types:
    - <xref:azure.ai.ml.exceptions.ErrorTarget>
- uid: azure.ai.ml.entities.job_errors.JobParsingError.continuation_token
  name: continuation_token
  signature: 'continuation_token: str | None'
- uid: azure.ai.ml.entities.job_errors.JobParsingError.exc_msg
  name: exc_msg
  signature: 'exc_msg: str'
- uid: azure.ai.ml.entities.job_errors.JobParsingError.exc_traceback
  name: exc_traceback
  signature: 'exc_traceback: TracebackType | None'
- uid: azure.ai.ml.entities.job_errors.JobParsingError.exc_type
  name: exc_type
  signature: 'exc_type: Type[Any] | None'
- uid: azure.ai.ml.entities.job_errors.JobParsingError.exc_value
  name: exc_value
  signature: 'exc_value: BaseException | None'
- uid: azure.ai.ml.entities.job_errors.JobParsingError.inner_exception
  name: inner_exception
  signature: 'inner_exception: BaseException | None'
- uid: azure.ai.ml.entities.job_errors.JobParsingError.message
  name: message
  signature: 'message: str | None'
