### YamlMime:PythonClass
uid: azure.ai.ml.exceptions.ValidationException
name: ValidationException
fullName: azure.ai.ml.exceptions.ValidationException
module: azure.ai.ml.exceptions
inheritances:
- azure.ai.ml.exceptions.MlException
constructor:
  syntax: 'ValidationException(message: str, no_personal_data_message: str, *args,
    error_type: azure.ai.ml.exceptions.ValidationErrorType = <ValidationErrorType.GENERIC:
    ''GENERIC''>, target: azure.ai.ml.exceptions.ErrorTarget = ''Unknown'', error_category:
    azure.ai.ml.exceptions.ErrorCategory = ''UserError'', **kwargs)'
  parameters:
  - name: message
  - name: no_personal_data_message
attributes:
- uid: azure.ai.ml.exceptions.ValidationException.error_type
  name: error_type
  summary: Return the error type.
  return:
    description: The error type.
    types:
    - <xref:azure.ai.ml.exceptions.ValidationErrorType>
